name: Check Secrets
on: push

jobs:
  filter-targets:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      TARGET_ENV_LIST: '["env_1", "env_2"]'
      TARGET: 'DEV'
    steps:
      - name: Filter env
        uses: actions/github-script@v6
        with:
          script: |-
            const {TARGET_ENV_LIST, TARGET} = process.env
            const targetEnvList = JSON.parse(TARGET_ENV_LIST)
            console.log(targetEnvList)
