name: Check Secrets
on: push

jobs:
  filter-targets:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions: read-all
    env:
      TARGET_ENV_LIST: '["env_1", "env_2"]'
      TARGET: 'DEV'
      REPO_ID: ${{github.repository_id}}
    steps:
      - name: Filter env
        uses: actions/github-script@v6
        with:
          script: |-
            const {TARGET_ENV_LIST, TARGET, REPO_ID} = process.env
            const targetEnvList = JSON.parse(TARGET_ENV_LIST)
            console.log(targetEnvList)

  in-env:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        env: ${{fromJson('["env_1", "env_2"]')}}
        target: [DEV, STG, PROD]
    environment: ${{matrix.env}}
    env:
      TOKEN: >-
        ${{
          matrix.target == 'DEV' && secrets.DEV || 
          matrix.target == 'STG' && secrets.STG || 
          matrix.target == 'PROD' && secrets.PROD
        }}
    steps:
      - name: Check token
        run: echo ${{env.TOKEN}}
        if: ${{env.TOKEN}}
