name: Check Secrets
on: push

jobs:
  filter-targets:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
      id-token: write
      repository-projects: read
    env:
      TARGET_ENV_LIST: '["env_1", "env_2"]'
      TARGET: 'DEV'
      REPO_ID: ${{github.repository_id}}
    steps:
      - name: Filter env
        uses: actions/github-script@v6
        with:
          script: |-
            const {TARGET_ENV_LIST, TARGET, REPO_ID} = process.env
            const targetEnvList = JSON.parse(TARGET_ENV_LIST)
            console.log(targetEnvList)
            for(const env of targetEnvList){
              secrets = await github.rest.actions.listEnvironmentSecrets({
                repository_id: REPO_ID,
                environment_name: env,
              });
              console.log(env)
              console.log(secrets)
            }
