name: Cool

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        options:
          - dev
          - stg
          - prod
      country:
        type: string
        required: false

jobs:
  show-input:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        country: ${{ fromJson(format('["{0}"]', inputs.country) || '["jp", "gb", "us"]' )}}
    steps:
      - name: Echo Input
        run: echo $INPUT | jq
        env:
          INPUT: ${{toJson(inputs)}}
